---
title: "R Notebook"
output: html_notebook
---

# input and libraries
```{r}
library(survival)
library(dplyr)
library(ggplot2)
library(survminer)

## kidney only
## for some reason read.table didn't work
setwd("/Users/jiemingchen/Documents/transplantation/a_donor/immport/survival")
data.outcome <- read.delim("final.iTx.posttx_outcomes.v5.kidney.txt", header = T, sep = "\t")

```

# survival analyses
## input data
```{r}
## do survival analysis for those with:
## (1) everything
## (2) subsets
## New_Hypertension_Diagnosis = CMP_NHYPDX
## Diabetes_Mellitus          = CMP_DIABETES_MELLITUS
## Postoperative_Ileus        = CMP_POP_ILEUS
## Proteinuria                = CMP_RENAL_PROTEIN
## Stroke                     = CMP_STROKE
## Dysrhythmia                = CMP_DYSR
do.ht <- data.outcome %>% filter(CMP_NHYPDX == "Yes") %>% 
                                    mutate(outcome = "New_Hypertension")
do.dm <- data.outcome %>% filter(CMP_DIABETES_MELLITUS == "Yes") %>% 
                                    mutate(outcome = "Diabetes_Mellitus")
do.il <- data.outcome %>% filter(CMP_POP_ILEUS == "Yes") %>% 
                                    mutate(outcome = "Postoperative_Ileus")
do.pu <- data.outcome %>% filter(CMP_RENAL_PROTEIN == "Yes") %>% 
                                    mutate(outcome = "Proteinuria")
do.st <- data.outcome %>% filter(CMP_STROKE == "Yes") %>% 
                                    mutate(outcome = "Stroke")
do.dy <- data.outcome %>% filter(CMP_DYSR == "Yes") %>% 
                                    mutate(outcome = "Dysrhythmia")

### this combination has redundancies cos there are individuals with multiple outcomes
do.z.redun <- rbind(do.ht,do.dm,do.il,do.pu,do.st,do.dy)


## (3) if one or more of 
## New_Hypertension_Diagnosis = CMP_NHYPDX
## Diabetes_Mellitus          = CMP_DIABETES_MELLITUS
## Postoperative_Ileus        = CMP_POP_ILEUS
## Proteinuria                = CMP_RENAL_PROTEIN
## Stroke                     = CMP_STROKE
## Dysrhythmia                = CMP_DYSR
do.multiple <- data.outcome %>% 
                       filter(CMP_NHYPDX == "Yes" |
                              CMP_DIABETES_MELLITUS == "Yes" |
                              CMP_POP_ILEUS == "Yes" |
                              CMP_RENAL_PROTEIN == "Yes" |
                              CMP_STROKE == "Yes" |
                              CMP_DYSR == "Yes") %>%
                       mutate(CMP_NHYPDX1 = ifelse(CMP_NHYPDX == "Yes",1,0)) %>%
                       mutate(CMP_DIABETES_MELLITUS1 = ifelse(CMP_DIABETES_MELLITUS == "Yes",1,0)) %>%
                       mutate(CMP_POP_ILEUS1 = ifelse(CMP_POP_ILEUS == "Yes",1,0)) %>%
                       mutate(CMP_RENAL_PROTEIN1 = ifelse(CMP_RENAL_PROTEIN == "Yes",1,0)) %>%
                       mutate(CMP_STROKE1 = ifelse(CMP_STROKE == "Yes",1,0)) %>%
                       mutate(CMP_DYSR1 = ifelse(CMP_DYSR == "Yes",1,0)) %>%
                       mutate(multipleDiseases = CMP_NHYPDX1 + CMP_DIABETES_MELLITUS1 +
                                                 CMP_POP_ILEUS1 + CMP_RENAL_PROTEIN1 +
                                                 CMP_STROKE1 + CMP_DYSR1)

## proportion of people with 1 or 2 or 3 bignode diseases
do.multiple %>% ggplot(aes(x = multipleDiseases)) + geom_bar(aes(y = ..count../sum(..count..)))



```

## variable prep
```{r}
## max days posttx -- 40 years = 14600 days
## ceiling(maxtime/365/5) * 5
maxtime = max(na.omit(data.outcome$CMP_POPRF_DOO_MIN),
              na.omit(data.outcome$CMP_POPDIAL_DOO_MIN),
              na.omit(data.outcome$CMP_DO_LIST_MIN),
              na.omit(data.outcome$CMP_DOTRANSP_MIN),
              na.omit(data.outcome$CMP_CMD_DOO_MIN))

```

## define survival endpoints and functions
```{r}
## define 4 ESRD endpoints
## CMP_POP_RF   = Post-operative_Renal_Failure
## CMP_POP_DIAL = Post-operative_Dialysis
## CMP_LIST	    = kidney_transplant_waitinglist
## CMP_CMD	    = Chronic/Maintenance_Dialysis
## create 2 new cols 
## (1) event - if subject has either one of the ESRD
## (2) time  - if subject has at least one timing available signifying ESRD, if multiple timings, take the earliest onset of the ESRD
data.outcome.surv <- data.outcome %>% 
                      mutate(event = ifelse(CMP_POP_RF == "Yes" |
                                            CMP_POP_DIAL == "Yes" |
                                            CMP_LIST == "Yes" |
                                            CMP_REC_TRANS == "Yes" |
                                            CMP_CMD == "Yes", 1, 0)) %>%
                      mutate(time = ifelse(event == 0, ceiling(maxtime/365/5) * 5 * 365, 
                                    ifelse(CMP_POPRF_DOO_MIN == "NA" & 
                                           CMP_POPDIAL_DOO_MIN == "NA" & 
                                           CMP_DO_LIST_MIN == "NA" & 
                                           CMP_DOTRANSP_MIN == "NA" & 
                                           CMP_CMD_DOO_MIN == "NA", NA, 
                                          pmin(CMP_POPRF_DOO_MIN,
                                               CMP_POPDIAL_DOO_MIN,
                                               CMP_DO_LIST_MIN,
                                               CMP_DOTRANSP_MIN,
                                               CMP_CMD_DOO_MIN, na.rm = T)))) %>%
                      select(Sub_Org_Accession, event, time)

## do.z.redundant
do.z.redun.surv <- do.z.redun %>% 
                      mutate(event = ifelse(CMP_POP_RF == "Yes" |
                                            CMP_POP_DIAL == "Yes" |
                                            CMP_LIST == "Yes" |
                                            CMP_REC_TRANS == "Yes" |
                                            CMP_CMD == "Yes", 1, 0)) %>%
                      mutate(time = ifelse(event == 0, ceiling(maxtime/365/5) * 5 * 365, 
                                    ifelse(CMP_POPRF_DOO_MIN == "NA" & 
                                           CMP_POPDIAL_DOO_MIN == "NA" & 
                                           CMP_DO_LIST_MIN == "NA" & 
                                           CMP_DOTRANSP_MIN == "NA" & 
                                           CMP_CMD_DOO_MIN == "NA", NA, 
                                          pmin(CMP_POPRF_DOO_MIN,
                                               CMP_POPDIAL_DOO_MIN,
                                               CMP_DO_LIST_MIN,
                                               CMP_DOTRANSP_MIN,
                                               CMP_CMD_DOO_MIN, na.rm = T)))) %>%
                      select(Sub_Org_Accession, event, time, outcome)

## do.multiple
do.multiple.surv <- do.multiple %>% 
                      mutate(event = ifelse(CMP_POP_RF == "Yes" |
                                            CMP_POP_DIAL == "Yes" |
                                            CMP_LIST == "Yes" |
                                            CMP_REC_TRANS == "Yes" |
                                            CMP_CMD == "Yes", 1, 0)) %>%
                      mutate(time = ifelse(event == 0, ceiling(maxtime/365/5) * 5 * 365, 
                                    ifelse(CMP_POPRF_DOO_MIN == "NA" & 
                                           CMP_POPDIAL_DOO_MIN == "NA" & 
                                           CMP_DO_LIST_MIN == "NA" & 
                                           CMP_DOTRANSP_MIN == "NA" & 
                                           CMP_CMD_DOO_MIN == "NA", NA, 
                                          pmin(CMP_POPRF_DOO_MIN,
                                               CMP_POPDIAL_DOO_MIN,
                                               CMP_DO_LIST_MIN,
                                               CMP_DOTRANSP_MIN,
                                               CMP_CMD_DOO_MIN, na.rm = T)))) %>%
                      select(Sub_Org_Accession, event, time, multipleDiseases)

```

## plot survival Kaplan Meier curve
```{r}
# survival fxn of outcomes

## (1) all
data.outcome.surv.table <- Surv(data.outcome.surv$time/365, data.outcome.surv$event) ## survival table
fit <- survfit(data.outcome.surv.table~1)
summary(fit)
plot(fit, xlab="t", ylab=expression(hat(S)*"(t)"), ylim = c(0.98,1)) ## base plot
ggsurvplot(fit, data = data.outcome.surv, risk.table = T, ylim = c(0.98,1)) ## survminer

## (2) subsets
do.z.redun.surv.table <- Surv(do.z.redun.surv$time/365, do.z.redun.surv$event) ## survival table
fit <- survfit(do.z.redun.surv.table ~ outcome, data = do.z.redun.surv)
summary(fit)
p <- ggsurvplot(
  fit, 
  xlab = 'Time (years)',
  data = do.z.redun.surv, 
  # conf.int = T,
  size = 1, 
  legend.labs = c("Diabetes_Mellitus","Dysrhythmia",
                  "New_Hypertension","Postoperative_Ileus",
                  "Proteinuria","Stroke"),
  ggtheme = theme_bw(),
  risk.table = T, 
  ylim = c(0.9,1)) ## survminer

print(p)

## (3) multiple diseases
do.multiple.surv.table <- Surv(do.multiple.surv$time/365, do.multiple.surv$event) ## survival table
fit <- survfit(do.multiple.surv.table ~ multipleDiseases, data = do.multiple.surv)
summary(fit)
p <- ggsurvplot(
  fit, 
  xlab = 'Time (years)',
  data = do.multiple.surv, 
  # conf.int = T,
  palette = "Set2",
  size = 1, 
  legend.labs = c("1","2","3","4","5"),
  ggtheme = theme_bw(),
  risk.table = T, 
  ylim = c(0.9,1)) ## survminer

print(p)

```



# R example data
```{r example}
data(ovarian)
## Create a survival object using Surv
## a plus sign suffixed for every censored data
S1 = Surv(ovarian$futime, ovarian$fustat)
S1

## remove all censored data
fit1 = survfit(S1~1)
summary(fit1)
plot(fit1, xlab="t", ylab=expression(hat(S)*"(t)"))


## doing parametric fitting 
## (use max likelihood estimation to est parameters in the model)
# exponential
s2 = survreg(S1~1, ovarian, dist="exponential")
summary(s2)
```

# another R example
```{r}
#fit a Kaplan-Meier and plot it
fit <- survfit(Surv(time, status) ~ x, data = aml) 
plot(fit, lty = 2:3) 
legend(100, .8, c("Maintained", "Nonmaintained"), lty = 2:3) 

#fit a Cox proportional hazards model and plot the  
#predicted survival for a 60 year old 
fit <- coxph(Surv(futime, fustat) ~ age, data = ovarian) 
plot(survfit(fit, newdata=data.frame(age=60)),
     xscale=365.25, xlab = "Years", ylab="Survival") 

# Here is the data set from Turnbull
#  There are no interval censored subjects, only left-censored (status=3),
#  right-censored (status 0) and observed events (status 1)
#
#                             Time
#                         1    2   3   4
# Type of observation
#           death        12    6   2   3
#          losses         3    2   0   3
#      late entry         2    4   2   5
#
tdata <- data.frame(time  =c(1,1,1,2,2,2,3,3,3,4,4,4),
                    status=rep(c(1,0,2),4),
                    n     =c(12,3,2,6,2,4,2,0,2,3,3,5))
fit  <- survfit(Surv(time, time, status, type='interval') ~1, 
              data=tdata, weight=n)

#
# Time to progression/death for patients with monoclonal gammopathy
#  Competing risk curves (cumulative incidence)
fitKM <- survfit(Surv(stop, event=='progression') ~1, data=mgus1,
                    subset=(start==0))

fitCI <- survfit(Surv(stop, status*as.numeric(event), type="mstate") ~1,
                    data=mgus1, subset=(start==0))

# CI curves are always plotted from 0 upwards, rather than 1 down
plot(fitCI, xscale=365.25, xmax=7300, mark.time=FALSE,
            col=2:3, xlab="Years post diagnosis of MGUS")
lines(fitKM, fun='event', xmax=7300, mark.time=FALSE,
            conf.int=FALSE)
text(10, .4, "Competing risk: death", col=3)
text(16, .15,"Competing risk: progression", col=2)
text(15, .30,"KM:prog")
```