---
title: "Untitled"
output: html_document
---

# input and libraries
```{r}
library(survival)
library(dplyr)
library(ggplot2)
library(survminer)
library(tidyr)

## save the old data.outcome
# saveRDS(data.outcome, "/Users/chenj220/Documents/ucsf/transplantation/a_donor/immport/survival/data_outcome_old.rds")

## kidney only
## for some reason read.table didn't work
data.outcome <- read.delim("/Users/chenj220/Documents/ucsf/transplantation/a_donor/immport/survival/final.iTx.posttx_outcomes.v5.kidney.txt", header = T, sep = "\t", stringsAsFactors = F)

##################
#### NETWORKS ####
##################
#### which individuals are in the networks
## input - relive only
outcomes <- read.table("/Users/chenj220/Documents/ucsf/transplantation/a_donor/immport/network_traj_analyses/immport2cytoscape/txp_immport2cytoscape_seq-merged-relive01_02_03_immport2tsv-noControls_outcomes_kidney.txt", sep = "\t", header = T, stringsAsFactors = F)

## subsetting
# those with no time points, excluding those lines with NA
outcomes.notimepoints <- outcomes %>%
                    filter(eventA_min == 5000000000 | eventB_min == 5000000000) %>%
                    filter(eventA_min != 5000000001 & eventB_min != 5000000001)
# those with time points
# this is my nw
outcomes.wtimepoints <- outcomes %>%
                    filter(eventA_min != 5000000000 & eventB_min != 5000000000) %>%
                    filter(eventA_min != 5000000001 & eventB_min != 5000000001)

a <- outcomes.wtimepoints %>% select(subject_ID, eventA)
b <- outcomes.wtimepoints %>% select(subject_ID, eventB)
names(a) <- c("subject_ID","event")
names(b) <- c("subject_ID","event")

node_info <- read.table("/Users/chenj220/Documents/ucsf/transplantation/a_donor/immport/network_traj_analyses/cytoscape/network_info/tx_LD_outcome_node_info.txt", sep = "\t", header = T, stringsAsFactors = F)
data.nw <- rbind(a,b) %>%
  filter(event != "transplant") %>%
  merge(node_info)

## retain only those used in the network
data.outcome.nw <- data.outcome %>% 
  filter(data.outcome$Sub_Org_Accession %in% data.nw$subject_ID)

```



# survival analyses
## input data
```{r}
## do survival analysis for those with:
## (1) everything


## (2) if one or more of 
## New_Hypertension_Diagnosis = CMP_NHYPDX
## Diabetes_Mellitus          = CMP_DIABETES_MELLITUS
## Postoperative_Ileus        = CMP_POP_ILEUS
## Proteinuria                = CMP_RENAL_PROTEIN
## Stroke                     = CMP_STROKE
## Dysrhythmia                = CMP_DYSR
do.multiple <- data.outcome.nw %>% 
                       filter(CMP_NHYPDX == "Yes" |
                              CMP_DIABETES_MELLITUS == "Yes" |
                              CMP_POP_ILEUS == "Yes" |
                              CMP_RENAL_PROTEIN == "Yes" |
                              CMP_STROKE == "Yes" |
                              CMP_DYSR == "Yes") %>%
                       mutate(CMP_NHYPDX1 = ifelse(CMP_NHYPDX == "Yes",1,0)) %>%
                       mutate(CMP_DIABETES_MELLITUS1 = ifelse(CMP_DIABETES_MELLITUS == "Yes",1,0)) %>%
                       mutate(CMP_POP_ILEUS1 = ifelse(CMP_POP_ILEUS == "Yes",1,0)) %>%
                       mutate(CMP_RENAL_PROTEIN1 = ifelse(CMP_RENAL_PROTEIN == "Yes",1,0)) %>%
                       mutate(CMP_STROKE1 = ifelse(CMP_STROKE == "Yes",1,0)) %>%
                       mutate(CMP_DYSR1 = ifelse(CMP_DYSR == "Yes",1,0)) %>%
                       mutate(multipleDiseases = CMP_NHYPDX1 + CMP_DIABETES_MELLITUS1 + CMP_POP_ILEUS1 + CMP_RENAL_PROTEIN1 + CMP_STROKE1 + CMP_DYSR1)

## proportion of people with 1 or 2 or 3 bignode diseases
do.multiple %>% 
  ggplot(aes(x = multipleDiseases)) + 
  geom_bar(aes(y = ..count../sum(..count..)))



## (3) subsets; restricted to only those w only 1 condition (otherwise there will be multiple indivs with >1 dzs)
## New_Hypertension_Diagnosis = CMP_NHYPDX
## Diabetes_Mellitus          = CMP_DIABETES_MELLITUS
## Postoperative_Ileus        = CMP_POP_ILEUS
## Proteinuria                = CMP_RENAL_PROTEIN
## Stroke                     = CMP_STROKE
## Dysrhythmia                = CMP_DYSR
data.outcome.nw.1dz <- do.multiple %>% filter(multipleDiseases == 1)
do.ht <- data.outcome.nw.1dz %>% filter(CMP_NHYPDX == "Yes") %>% 
                                    mutate(outcome = "New_Hypertension")
do.dm <- data.outcome.nw.1dz %>% filter(CMP_DIABETES_MELLITUS == "Yes") %>% 
                                    mutate(outcome = "Diabetes_Mellitus")
do.il <- data.outcome.nw.1dz %>% filter(CMP_POP_ILEUS == "Yes") %>% 
                                    mutate(outcome = "Postoperative_Ileus")
do.pu <- data.outcome.nw.1dz %>% filter(CMP_RENAL_PROTEIN == "Yes") %>% 
                                    mutate(outcome = "Proteinuria")
do.st <- data.outcome.nw.1dz %>% filter(CMP_STROKE == "Yes") %>% 
                                    mutate(outcome = "Stroke")
do.dy <- data.outcome.nw.1dz %>% filter(CMP_DYSR == "Yes") %>% 
                                    mutate(outcome = "Dysrhythmia")

do.z.1dz <- rbind(do.ht,do.dm,do.il,do.pu,do.st,do.dy)

```

# DEATH INFO
```{r}
death_kidney <- read.delim("/Users/chenj220/Documents/ucsf/transplantation/a_donor/immport/survival/final.iTx.posttx_outcomes.v5.txt", stringsAsFactors = F, header = T, sep = "\t") %>% 
  filter(Organ == "kidney") %>%
  select(Sub_Org_Accession,PSO_LAST_STATUS,PSO_DL_ALIVE_MIN,PSO_DL_ALIVE_MAX,PSO_NODL_ALIVE,PSO_DO_DEATH_MIN,PSO_DO_DEATH_MAX,PSO_NOD0_DEATH,PSO_MATCHDEAD_DATE_MIN,PSO_MATCHDEAD_DATE_MAX,CAN_DEATH_DT_MIN,CAN_DEATH_DT_MAX,PSO_PRIM_COD,PSO_PRIM_CODOTH,PSO_SEC_COD,PSO_SEC_CODOTH,PSO_TERT_COD,PSO_TERT_CODOTH,CAN_REM_COD,DON_LIVING_DON_COD,DON_STAT,DON_STAT_DT_MIN,DON_STAT_DT_MAX,NDIDEATH_MIN,NDIDEATH_MAX,DEATHDATE_MIN,DEATHDATE_MAX,DEATHPRIMARYCAUSE,DEATHPRIMARYCAUSEOTHER,DEATHSECONDARYCAUSE,DEATHSECONDARYCAUSEOTHER) %>%
  filter(PSO_LAST_STATUS != "Alive")

## check for missingness as proportion
## NDI DEATH has least missingness! Use max as date
a <- as.data.frame(apply(death_kidney, 2, function(x) (sum(is.na(x))/length(x))*100))

## samples with death days after tx using NDI
death_kidney <- death_kidney %>%
  select(Sub_Org_Accession, NDIDEATH_MAX)
```


## variable prep
```{r}
## max days posttx -- 40 years = 14600 days
## ceiling(maxtime/365/5) * 5
maxtime <- max(na.omit(data.outcome$CMP_POPRF_DOO_MIN),
              na.omit(data.outcome$CMP_POPDIAL_DOO_MIN),
              na.omit(data.outcome$CMP_DO_LIST_MIN),
              na.omit(data.outcome$CMP_DOTRANSP_MIN),
              na.omit(data.outcome$CMP_CMD_DOO_MIN))

```

## define survival endpoints and functions
```{r}
## define 4 ESRD endpoints
## CMP_POP_RF   = Post-operative_Renal_Failure
## CMP_POP_DIAL = Post-operative_Dialysis
## CMP_LIST	    = kidney_transplant_waitinglist
## CMP_CMD	    = Chronic/Maintenance_Dialysis
## create 2 new cols 
## (1) event - if subject has either one of the ESRD
## (2) time  - if subject has at least one timing available signifying ESRD, if multiple timings, take the earliest onset of the ESRD
data.outcome.nw.surv <- data.outcome.nw %>% 
                      mutate(event = ifelse(CMP_POP_RF == "Yes" |
                                            CMP_POP_DIAL == "Yes" |
                                            CMP_LIST == "Yes" |
                                            CMP_REC_TRANS == "Yes" |
                          ## event == 3, interval-censored
                                            CMP_CMD == "Yes", 1, 3)) %>%
                          ## if they are alive at end of max time, they are censored at the end
                      mutate(time = ifelse(event == 3 | event == 1, ceiling(maxtime/365/5) * 5 * 365, 
                                    ifelse(CMP_POPRF_DOO_MIN == "NA" & 
                                           CMP_POPDIAL_DOO_MIN == "NA" & 
                                           CMP_DO_LIST_MIN == "NA" & 
                                           CMP_DOTRANSP_MIN == "NA" & 
                                           CMP_CMD_DOO_MIN == "NA", NA, 
                                          pmin(CMP_POPRF_DOO_MIN,
                                               CMP_POPDIAL_DOO_MIN,
                                               CMP_DO_LIST_MIN,
                                               CMP_DOTRANSP_MIN,
                                               CMP_CMD_DOO_MIN, na.rm = T)))) %>%
                      select(Sub_Org_Accession, event, time) %>% 
                      merge(death_kidney, all.x = T)

### check against the death registry
## for those death patients with event/status == 1 (ESRD) and in death registry, check if the death date is before the event 
status1   <- data.outcome.nw.surv %>% filter(event == 1)
status1_w <- merge(status1, death_kidney) ## 15 individuals in death registry
status1_w$NDIDEATH_MAX < status1_w$time ## none of the 15 deaths occur before event; status quo

## for those patients with event/status == 3 (alive, thus right-censored) and are in death registry, check if death occurs before trial ends at maxtime
# the NAs; no death date; right censored at maxtime; event == 0
status3   <- data.outcome.nw.surv %>% filter(event == 3) ## the NAs
status3_w <- merge(status3, death_kidney) ## there are 5 NAs
s3 <- status3_w[is.na(status3_w$NDIDEATH_MAX),] 
data.outcome.nw.surv[data.outcome.nw.surv$Sub_Org_Accession %in% s3$Sub_Org_Accession,"event"] <- 0

# the FALSEs; death occurs after maxtime == interval-censored - remains at 3
table(status3_w$NDIDEATH_MAX < status3_w$time) ## there are 4 FALSEs; 
na.omit(status3_w[status3_w$NDIDEATH_MAX >= status3_w$time,]) ## the FALSEs; remains at 3 so status quo

# TRUEs shld be all right censored (event = 0) cos death occurs before event
# time = time of death
s3_trues_0 <- status3_w[na.omit(status3_w$NDIDEATH_MAX < status3_w$time),] %>% ## TRUEs shld be all right censored cos death occurs before maxtime; so event == 0 at time of death
  filter(!is.na(NDIDEATH_MAX))
data.outcome.nw.surv[data.outcome.nw.surv$Sub_Org_Accession %in% s3_trues_0$Sub_Org_Accession,"event"] <- 0

data.outcome.nw.surv <- data.outcome.nw.surv %>%
  mutate(time_final = ifelse(data.outcome.nw.surv$Sub_Org_Accession %in% s3_trues_0$Sub_Org_Accession, NDIDEATH_MAX, time))


###__--------------------------------------------
## do.z.1dz
do.z.1dz.surv <- do.z.1dz %>% 
                      mutate(event = ifelse(CMP_POP_RF == "Yes" |
                                            CMP_POP_DIAL == "Yes" |
                                            CMP_LIST == "Yes" |
                                            CMP_REC_TRANS == "Yes" |
                                            CMP_CMD == "Yes", 1, 3)) %>%
                      mutate(time = ifelse(event == 3 | event == 1, ceiling(maxtime/365/5) * 5 * 365, 
                                    ifelse(CMP_POPRF_DOO_MIN == "NA" & 
                                           CMP_POPDIAL_DOO_MIN == "NA" & 
                                           CMP_DO_LIST_MIN == "NA" & 
                                           CMP_DOTRANSP_MIN == "NA" & 
                                           CMP_CMD_DOO_MIN == "NA", NA, 
                                          pmin(CMP_POPRF_DOO_MIN,
                                               CMP_POPDIAL_DOO_MIN,
                                               CMP_DO_LIST_MIN,
                                               CMP_DOTRANSP_MIN,
                                               CMP_CMD_DOO_MIN, na.rm = T)))) %>%
                      select(Sub_Org_Accession, event, time, outcome) %>% 
                      merge(death_kidney, all.x = T)

### check against the death registry
## for those death patients with event/status == 1 (ESRD) and in death registry, check if the death date is before the event 
status1   <- do.z.1dz.surv %>% filter(event == 1)
status1_w <- merge(status1, death_kidney) ## 3 individuals in death registry
status1_w$NDIDEATH_MAX < status1_w$time ## none of the 3 deaths occur before event; status quo

## for those patients with event/status == 3 (alive, thus right-censored) and are in death registry, check if death occurs before trial ends at maxtime; status quo
# the NAs; no death date; right censored at maxtime; event == 0; no such thing so status quo
status3   <- do.z.1dz.surv %>% filter(event == 3) ## the NAs
status3_w <- merge(status3, death_kidney) ## 61 indivi in death registry
status3_w[is.na(status3_w$NDIDEATH_MAX),]  ## 0 NAs


# the FALSEs; death occurs after maxtime == interval-censored - remains at 3
table(status3_w$NDIDEATH_MAX < status3_w$time) ## there are 4 FALSEs; 
na.omit(status3_w[status3_w$NDIDEATH_MAX >= status3_w$time,]) ## the FALSEs; remains at 3 so status quo

# TRUEs shld be all right censored (event = 0) cos death occurs before event
# time = time of death
s3_trues_0 <- status3_w[na.omit(status3_w$NDIDEATH_MAX < status3_w$time),] %>% ## TRUEs shld be all right censored cos death occurs before maxtime; so event == 0 at time of death
  filter(!is.na(NDIDEATH_MAX))
do.z.1dz.surv[do.z.1dz.surv$Sub_Org_Accession %in% s3_trues_0$Sub_Org_Accession,"event"] <- 0

do.z.1dz.surv <- do.z.1dz.surv %>%
  mutate(time_final = ifelse(do.z.1dz.surv$Sub_Org_Accession %in% s3_trues_0$Sub_Org_Accession, NDIDEATH_MAX, time))

###__--------------------------------------------
## do.multiple
do.multiple.surv <- do.multiple %>% 
                      mutate(event = ifelse(CMP_POP_RF == "Yes" |
                                            CMP_POP_DIAL == "Yes" |
                                            CMP_LIST == "Yes" |
                                            CMP_REC_TRANS == "Yes" |
                                            CMP_CMD == "Yes", 1, 3)) %>%
  ## if event is ESRD or alive, with no time, set to max time
                      mutate(time = ifelse(event == 3 | event == 1, ceiling(maxtime/365/5) * 5 * 365, 
                                    ifelse(CMP_POPRF_DOO_MIN == "NA" & 
                                           CMP_POPDIAL_DOO_MIN == "NA" & 
                                           CMP_DO_LIST_MIN == "NA" & 
                                           CMP_DOTRANSP_MIN == "NA" & 
                                           CMP_CMD_DOO_MIN == "NA", NA, 
                                          pmin(CMP_POPRF_DOO_MIN,
                                               CMP_POPDIAL_DOO_MIN,
                                               CMP_DO_LIST_MIN,
                                               CMP_DOTRANSP_MIN,
                                               CMP_CMD_DOO_MIN, na.rm = T)))) %>%
                      select(Sub_Org_Accession, event, time, multipleDiseases) %>% 
                      merge(death_kidney, all.x = T)

### check against the death registry
## for those death patients with event/status == 1 (ESRD) and in death registry, check if the death date is before the event 
status1   <- do.multiple.surv %>% filter(event == 1)
status1_w <- merge(status1, death_kidney) ## 6 individuals in death registry
status1_w$NDIDEATH_MAX < status1_w$time ## none of the 6 deaths occur before event; status quo

## for those patients with event/status == 3 (alive, thus right-censored) and are in death registry, check if death occurs before trial ends at maxtime; status quo
# the NAs; no death date; right censored at maxtime; event == 0; no such thing so status quo
status3   <- do.multiple.surv %>% filter(event == 3) ## the NAs
status3_w <- merge(status3, death_kidney) ## 103 indivi in death registry
status3_w[is.na(status3_w$NDIDEATH_MAX),]  ## 2 NAs with no death date
s3 <- status3_w[is.na(status3_w$NDIDEATH_MAX),] 
do.multiple.surv[do.multiple.surv$Sub_Org_Accession %in% s3$Sub_Org_Accession,"event"] <- 0

# the FALSEs; death occurs after maxtime == interval-censored - remains at 3
table(status3_w$NDIDEATH_MAX < status3_w$time) ## there are 4 FALSEs; 
na.omit(status3_w[status3_w$NDIDEATH_MAX >= status3_w$time,]) ## the FALSEs; remains at 3 so status quo

# TRUEs shld be all right censored (event = 0) cos death occurs before event
# time = time of death
s3_trues_0 <- status3_w[na.omit(status3_w$NDIDEATH_MAX < status3_w$time),] %>% ## TRUEs shld be all right censored cos death occurs before maxtime; so event == 0 at time of death
  filter(!is.na(NDIDEATH_MAX))
do.multiple.surv[do.multiple.surv$Sub_Org_Accession %in% s3_trues_0$Sub_Org_Accession,"event"] <- 0

do.multiple.surv <- do.multiple.surv %>%
  mutate(time_final = ifelse(do.multiple.surv$Sub_Org_Accession %in% s3_trues_0$Sub_Org_Accession, NDIDEATH_MAX, time))

```




## plot survival Kaplan Meier curve
```{r}
# survival fxn of outcomes


## (1) data.outcome.nw.surv
## (3) do.multiple.surv
## (2) do.z.1dz.surv

## (1) all
data.outcome.nw.surv.tmpp <- data.outcome.nw.surv
data.outcome.nw.surv.tmpp[data.outcome.nw.surv.tmpp$event == 3, "event"] <- 0
data.outcome.surv.table <- Surv(data.outcome.nw.surv.tmpp$time_final/365, data.outcome.nw.surv.tmpp$event) ## survival table
fit <- survfit(data.outcome.nw.surv.tmpp ~ 1)
summary(fit)
plot(fit, xlab="t", ylab=expression(hat(S)*"(t)"), ylim = c(0.98,1)) ## base plot
ggsurvplot(fit, data = data.outcome.nw.surv.tmpp, risk.table = T, ylim = c(0.98,1)) ## survminer

```

```{r}
## (2) subsets
do.z.1dz.surv.table <- Surv(do.z.1dz.surv$time_final/365, do.z.1dz.surv$event) ## survival table
fit <- survfit(do.z.1dz.surv.table ~ outcome, data = do.z.1dz.surv)
summary(fit)
p <- ggsurvplot(
  fit, 
  xlab = 'Time (years)',
  data = do.z.1dz.surv, 
  # conf.int = T,
  size = 1, 
  legend.labs = c("Diabetes_Mellitus","Dysrhythmia",
                  "New_Hypertension","Postoperative_Ileus",
                  "Proteinuria","Stroke"),
  ggtheme = theme_bw(),
  risk.table = T, 
  ylim = c(0.9,1)) ## survminer

print(p)

## (3) multiple diseases
do.multiple.surv.table <- Surv(do.multiple.surv$time_final/365, do.multiple.surv$event) ## survival table
fit <- survfit(do.multiple.surv.table ~ multipleDiseases, data = do.multiple.surv)
summary(fit)
p <- ggsurvplot(
  fit, 
  xlab = 'Time (years)',
  data = do.multiple.surv, 
  # conf.int = T,
  palette = "Set2",
  size = 1, 
  legend.labs = c("1","2","3","4","5"),
  ggtheme = theme_bw(),
  risk.table = T, 
  ylim = c(0.9,1)) ## survminer

print(p)

```


## if one or more of cardiovascular and renal events
```{r}
## (3) if one or more of 
## New_Hypertension_Diagnosis = CMP_NHYPDX
## Diabetes_Mellitus          = CMP_DIABETES_MELLITUS
## Proteinuria                = CMP_RENAL_PROTEIN
## Stroke                     = CMP_STROKE
## Dysrhythmia                = CMP_DYSR
## Myocardial infarction      = CMP_MI
## Cardiac Arrest             = CMP_CARDARR
## Hematuria                  = CMP_RENAL_HEMT
## Nephrolithiasis            = CMP_RENAL_NEPH
## Microalbuminuria           = CMP_RENAL_MICRO

## Chronic/Maintenance Dialysis
## Post-operative renal failure
## Kidney waiting list
## Kidney tx
do.multiple_cardio <- data.outcome.nw %>% 
                       filter(CMP_NHYPDX == "Yes" | 
                              CMP_DIABETES_MELLITUS == "Yes" | 
                              CMP_RENAL_PROTEIN == "Yes" | 
                              CMP_STROKE == "Yes" | 
                              CMP_DYSR == "Yes" | 
                              CMP_MI == "Yes" | 
                              CMP_CARDARR == "Yes" | 
                              CMP_RENAL_HEMT == "Yes" | 
                              CMP_RENAL_NEPH == "Yes" | 
                              CMP_RENAL_MICRO == "Yes") %>%
                       mutate(CMP_EPIDIDYMITIS1 = ifelse( CMP_EPIDIDYMITIS == "Yes",1,0)) %>% 
                      mutate(CMP_POP_RETUB1 = ifelse( CMP_POP_RETUB == "Yes",1,0)) %>% 
                      mutate(CMP_CARDARR1 = ifelse( CMP_CARDARR == "Yes",1,0)) %>% 
                      mutate(CMP_STROKE1 = ifelse( CMP_STROKE == "Yes",1,0)) %>% 
                      mutate(CMP_PULEM1 = ifelse( CMP_PULEM == "Yes",1,0)) %>% 
                      mutate(CMP_MI1 = ifelse( CMP_MI == "Yes",1,0)) %>% 
                      mutate(CMP_BLAD1 = ifelse( CMP_BLAD == "Yes",1,0)) %>% 
                      mutate(CMP_BOWEL1 = ifelse( CMP_BOWEL == "Yes",1,0)) %>% 
                      mutate(CMP_SPLEN1 = ifelse( CMP_SPLEN == "Yes",1,0)) %>% 
                      mutate(CMP_VASCU1 = ifelse( CMP_VASCU == "Yes",1,0)) %>% 
                      mutate(CMP_WNDDEH1 = ifelse( CMP_WNDDEH == "Yes",1,0)) %>% 
                      mutate(CMP_WNDSER1 = ifelse( CMP_WNDSER == "Yes",1,0)) %>% 
                      mutate(CMP_PNTHX1 = ifelse( CMP_PNTHX == "Yes",1,0)) %>% 
                      mutate(CMP_COMP_INTUB1 = ifelse( CMP_COMP_INTUB == "Yes",1,0)) %>% 
                      mutate(CMP_INCHER1 = ifelse( CMP_INCHER == "Yes",1,0)) %>% 
                      mutate(CMP_REOP_INCHER1 = ifelse( CMP_REOP_INCHER == "Yes",1,0)) %>% 
                      mutate(CMP_CIP1 = ifelse( CMP_CIP == "Yes",1,0)) %>% 
                      mutate(CMP_TESTPN1 = ifelse( CMP_TESTPN == "Yes",1,0)) %>% 
                      mutate(CMP_PANCREAT1 = ifelse( CMP_PANCREAT == "Yes",1,0)) %>% 
                      mutate(CMP_RHAB1 = ifelse( CMP_RHAB == "Yes",1,0)) %>% 
                      mutate(CMP_POP_RF1 = ifelse( CMP_POP_RF == "Yes",1,0)) %>% 
                      mutate(CMP_POP_DIAL1 = ifelse( CMP_POP_DIAL == "Yes",1,0)) %>% 
                      mutate(CMP_POP_DVT1 = ifelse( CMP_POP_DVT == "Yes",1,0)) %>% 
                      mutate(CMP_POP_HEM1 = ifelse( CMP_POP_HEM == "Yes",1,0)) %>% 
                      mutate(CMP_POP_ILEUS1 = ifelse( CMP_POP_ILEUS == "Yes",1,0)) %>% 
                      mutate(CMP_RENAL_HEMT1 = ifelse( CMP_RENAL_HEMT == "Yes",1,0)) %>% 
                      mutate(CMP_RENAL_MICRO1 = ifelse( CMP_RENAL_MICRO == "Yes",1,0)) %>% 
                      mutate(CMP_RENAL_PROTEIN1 = ifelse( CMP_RENAL_PROTEIN == "Yes",1,0)) %>% 
                      mutate(CMP_RENAL_NEPH1 = ifelse( CMP_RENAL_NEPH == "Yes",1,0)) %>% 
                      mutate(CMP_DYSR1 = ifelse( CMP_DYSR == "Yes",1,0)) %>% 
                      mutate(CMP_SD1 = ifelse( CMP_SD == "Yes",1,0)) %>% 
                      mutate(CMP_DIABETES_MELLITUS1 = ifelse( CMP_DIABETES_MELLITUS == "Yes",1,0)) %>%
                      mutate(CMP_LIST1 = ifelse( CMP_LIST == "Yes",1,0)) %>% 
                      mutate(CMP_REC_TRANS1 = ifelse( CMP_REC_TRANS == "Yes",1,0)) %>% 
                      mutate(CMP_CMD1 = ifelse( CMP_CMD == "Yes",1,0)) %>% 
                      mutate(CMP_NHYPDX1 = ifelse( CMP_NHYPDX == "Yes",1,0)) %>%
  select(Sub_Org_Accession, CMP_EPIDIDYMITIS1, CMP_POP_RETUB1, CMP_CARDARR1, CMP_STROKE1, CMP_PULEM1, CMP_MI1, CMP_BLAD1, CMP_BOWEL1, CMP_SPLEN1, CMP_VASCU1, CMP_WNDDEH1, CMP_WNDSER1, CMP_PNTHX1, CMP_COMP_INTUB1, CMP_INCHER1, CMP_REOP_INCHER1, CMP_CIP1, CMP_TESTPN1, CMP_PANCREAT1, CMP_RHAB1, CMP_POP_RF1, CMP_POP_DIAL1, CMP_POP_DVT1, CMP_POP_HEM1, CMP_POP_ILEUS1, CMP_RENAL_HEMT1, CMP_RENAL_MICRO1, CMP_RENAL_PROTEIN1, CMP_RENAL_NEPH1, CMP_DYSR1, CMP_SD1, CMP_DIABETES_MELLITUS1, CMP_LIST1, CMP_REC_TRANS1, CMP_CMD1, CMP_NHYPDX1)

do.multiple_cardio[is.na(do.multiple_cardio)] <- 0

do.multiple_cardio <- do.multiple_cardio %>%
  mutate(multipleDiseases = CMP_EPIDIDYMITIS1 + CMP_POP_RETUB1 + CMP_CARDARR1 + CMP_STROKE1 + CMP_PULEM1 + CMP_MI1 + CMP_BLAD1 + CMP_BOWEL1 + CMP_SPLEN1 + CMP_VASCU1 + CMP_WNDDEH1 + CMP_WNDSER1 + CMP_PNTHX1 + CMP_COMP_INTUB1 + CMP_INCHER1 + CMP_REOP_INCHER1 + CMP_CIP1 + CMP_TESTPN1 + CMP_PANCREAT1 + CMP_RHAB1 + CMP_POP_RF1 + CMP_POP_DIAL1 + CMP_POP_DVT1 + CMP_POP_HEM1 + CMP_POP_ILEUS1 + CMP_RENAL_HEMT1 + CMP_RENAL_MICRO1 + CMP_RENAL_PROTEIN1 + CMP_RENAL_NEPH1 + CMP_DYSR1 + CMP_SD1 + CMP_DIABETES_MELLITUS1 + CMP_LIST1 + CMP_REC_TRANS1 + CMP_CMD1 + CMP_NHYPDX1)
  

## proportion of people with the above diseases
do.multiple_cardio %>% 
  ggplot(aes(x = multipleDiseases)) + 
  geom_bar(aes(y = ..count../sum(..count..)))

## just the ones
do.multiple_cardio %>%
  filter(multipleDiseases == 3) %>%
  select(-multipleDiseases) %>% 
  gather(event, number, -Sub_Org_Accession) %>%
  filter(number != 0) %>%
  ggplot(aes(x = number, fill = event)) +
  geom_bar(aes(y = ..count../sum(..count..)))
```

# R example data
```{r example}
data(ovarian)
## Create a survival object using Surv
## a plus sign suffixed for every censored data
S1 <- Surv(ovarian$futime, ovarian$fustat)
S1

## remove all censored data
fit1 = survfit(S1~1)
summary(fit1)
plot(fit1, xlab="t", ylab=expression(hat(S)*"(t)"))


## doing parametric fitting 
## (use max likelihood estimation to est parameters in the model)
# exponential
s2 <- survreg(S1~1, ovarian, dist="exponential")
summary(s2)
```

# another R example
```{r}
#fit a Kaplan-Meier and plot it
fit <- survfit(Surv(time, status) ~ x, data = aml) 
plot(fit, lty = 2:3) 
legend(100, .8, c("Maintained", "Nonmaintained"), lty = 2:3) 

#fit a Cox proportional hazards model and plot the  
#predicted survival for a 60 year old 
fit <- coxph(Surv(futime, fustat) ~ age, data = ovarian) 
plot(survfit(fit, newdata=data.frame(age=60)),
     xscale=365.25, xlab = "Years", ylab="Survival") 

# Here is the data set from Turnbull
#  There are no interval censored subjects, only left-censored (status=3),
#  right-censored (status 0) and observed events (status 1)
#
#                             Time
#                         1    2   3   4
# Type of observation
#           death        12    6   2   3
#          losses         3    2   0   3
#      late entry         2    4   2   5
#
tdata <- data.frame(time  =c(1,1,1,2,2,2,3,3,3,4,4,4),
                    status=rep(c(1,0,2),4),
                    n     =c(12,3,2,6,2,4,2,0,2,3,3,5))
fit  <- survfit(Surv(time, time, status, type='interval') ~1, 
              data=tdata, weight=n)

#
# Time to progression/death for patients with monoclonal gammopathy
#  Competing risk curves (cumulative incidence)
fitKM <- survfit(Surv(stop, event=='progression') ~1, data=mgus1,
                    subset=(start==0))

fitCI <- survfit(Surv(stop, status*as.numeric(event), type="mstate") ~1,
                    data=mgus1, subset=(start==0))

# CI curves are always plotted from 0 upwards, rather than 1 down
plot(fitCI, xscale=365.25, xmax=7300, mark.time=FALSE,
            col=2:3, xlab="Years post diagnosis of MGUS")
lines(fitKM, fun='event', xmax=7300, mark.time=FALSE,
            conf.int=FALSE)
text(10, .4, "Competing risk: death", col=3)
text(16, .15,"Competing risk: progression", col=2)
text(15, .30,"KM:prog")
```

```{r}
require("survival")
fit <- survfit(Surv(time, status) ~ sex, data = lung)
ggsurvplot(fit, data = lung)
```