pca <- read.table("D:/GGCP_April2010/Practicals/Day1_Session4/1421samples-101740snps-hhs-r26_pca.txt", header=T, sep="\t")
sample <- read.table("D:/GGCP_April2010/Practicals/Day1_Session4/1421samples-hhs-hapmap2r26.txt", sep="\t", header=T)
map <- double(1421)
for (i in 1:1421){
   map[i] <- which(pca[,1] == as.character(sample[i,1]))
}
pca <- pca[map, -1]
africa <- which(sample[,4] == "Africa")
america <- which(sample[,4] == "America")
cs.asia <- which(sample[,4] == "Centl.S.Asia")
CEU <- which(sample[,4] == "CEU")
CHB <- which(sample[,4] == "CHB")
e.asia <- which(sample[,4] == "East Asia")
europe <- which(sample[,4] == "Europe")
JPT <- which(sample[,4] == "JPT")
m.east <- which(sample[,4] == "Middle East")
oceania <- which(sample[,4] == "Oceania")
CHS <- which(sample[,4] == "SGVP-CH")
INS <- which(sample[,4] == "SGVP-ID")
MAS <- which(sample[,4] == "SGVP-ML")
YRI <- which(sample[,4] == "YRI")
par(pty = "s")
plot(pca[,1], pca[,2], xlab = "First axis of variation", ylab = "Second axis of variation", type = "n", cex.lab = 1.5, xaxt = "n", yaxt = "n", main = "HapMap – HGDP – SGVP", cex.main = 1.5)
points(pca[africa,1], pca[africa,2], pch = 16, col = "gray50")
points(pca[cs.asia,1], pca[cs.asia,2], pch = 16, col = "lightblue")
points(pca[e.asia,1], pca[e.asia,2], pch = 16, col = "peru")
points(pca[europe,1], pca[europe,2], pch = 16, col = "cyan3")
points(pca[m.east,1], pca[m.east,2], pch = 16, col = 8)
points(pca[oceania,1], pca[oceania,2], pch = 16, col = "coral")
points(pca[YRI,1], pca[YRI,2], pch = 16, col = 1)
points(pca[CEU,1], pca[CEU,2], pch = 16, col = 5)
points(pca[CHB,1], pca[CHB,2], pch = 16, col = 6)
points(pca[JPT,1], pca[JPT,2], pch = 16, col = "mediumorchid")
points(pca[CHS,1], pca[CHS,2], pch = 16, col = 2)
points(pca[INS,1], pca[INS,2], pch = 16, col = 4)
points(pca[MAS,1], pca[MAS,2], pch = 16, col = 3)
points(pca[america,1], pca[america,2], pch = 16, col = "magenta")
legend(locator(1), c("CHS", "INS", "MAS", "CHB", "JPT", "East Asia", "Oceania", "Americas", "Central / South Asia", "Europe", "CEU", "Middle East", "Africa", "YRI"), col = c(2,4,3,6,"mediumorchid","peru","coral","magenta","lightblue","cyan3",5,8,"gray50",1), pch = 16, bty = "n", cex = 1.2) 
